LOCALITY_CENTER = {
    "id": "shell_select",
    "name": "selected store MacPherson",
    "lat": 1.33118255886657,
    "lng": 103.877758601196,
    "radius_km": 2,
}

LOCALITY_BOUNDS = {
    "north": 1.34915,
    "south": 1.31322,
    "east": 103.89573,
    "west": 103.85979,
}

CATCHMENT_SNAPSHOT = {
    "source": "OneMap API search results",
    "verified_on": "2026-04-22",
    "radius_km": 2,
    "nearby_schools_count": 12,
    "nearby_schools_examples": [
        "MindChamps Preschool @ MacPherson",
        "PCF Sparkletots Preschool @ MacPherson",
        "Cedar Girls' Secondary School",
        "Cedar Primary School",
        "Canossa Catholic Primary School",
        "Stamford American International School",
        "Maris Stella High School",
        "Bartley Secondary School",
        "Geylang Methodist School",
    ],
    "nearby_offices_business_parks_count": 3,
    "nearby_offices_business_parks_examples": [
        "Pines Industrial Building",
        "PSL Industrial Building",
        "MacPherson Road Post Office",
    ],
    "mrt_bus_stops_count": 27,
    "mrt_bus_stops_examples": [
        "Mattar MRT Station",
        "MacPherson MRT Station",
        "70119 bus stop",
        "70111 bus stop",
        "70049 bus stop",
        "70041 bus stop",
        "Bus stops along MacPherson Road and Upper Aljunied Road",
    ],
    "competing_convenience_retail_count": 4,
    "competing_convenience_retail_examples": [
        "MacPherson Mall",
        "Grantral Mall @ MacPherson",
        "Circuit Road Market & Food Centre",
        "Market & Hawker Centre at 89 Circuit Road",
    ],
    "residential_density_indicator": "High",
}

LOCALITY_PLACES = [
    {
        "id": "shell_select",
        "name": "selected store MacPherson",
        "type": "shell_select",
        "query": "MacPherson Singapore convenience store",
        "why_it_matters": "Main store where product demand is tested.",
    },
    {
        "id": "macpherson_mall",
        "name": "MacPherson Mall",
        "type": "mall",
        "query": "MacPherson Mall 401 MacPherson Road Singapore",
        "why_it_matters": "Retail and supermarket competitor footfall.",
    },
    {
        "id": "ibis_macpherson",
        "name": "ibis Styles Singapore on MacPherson",
        "type": "hotel",
        "query": "ibis Styles Singapore on MacPherson 401 MacPherson Road Singapore",
        "why_it_matters": "Hotel guests and staff may need late-night convenience items.",
    },
    {
        "id": "super_thai",
        "name": "Super Thai by Soi Aroy",
        "type": "restaurant",
        "query": "379 Upper Aljunied Road Singapore",
        "why_it_matters": "Restaurant visitors, staff, and delivery riders create lunch/dinner movement.",
    },
    {
        "id": "little_seeds",
        "name": "Little Seeds Preschool",
        "type": "preschool",
        "query": "Calvary Baptist Church 48 Wan Tho Avenue Singapore",
        "why_it_matters": "Parent pickup/drop-off creates predictable weekday movement.",
    },
    {
        "id": "st_johns_home",
        "name": "St John's Home for Elderly Persons",
        "type": "eldercare",
        "query": "1 Willow Avenue Singapore",
        "why_it_matters": "Care staff, visitors, volunteers, and elderly care needs.",
    },
    {
        "id": "circuit_road_market",
        "name": "Circuit Road Market & Food Centre",
        "type": "food_centre",
        "query": "Circuit Road Market and Food Centre 80 Circuit Road Singapore",
        "why_it_matters": "Resident food and market trips throughout the day.",
    },
    {
        "id": "mattar_mrt",
        "name": "Mattar MRT Station",
        "type": "transport",
        "query": "Mattar MRT Station Singapore",
        "why_it_matters": "Commuter movement into and out of the locality.",
    },
    {
        "id": "grantral_mall",
        "name": "Grantral Mall @ MacPherson",
        "type": "mall",
        "query": "601 MacPherson Road Singapore",
        "why_it_matters": "Nearby retail and grocery competitor cluster.",
    },
]


PLACES = [
    {
        "id": "shell_select",
        "name": "selected store Tampines Link",
        "type": "shell_select",
        "x": 52,
        "y": 48,
        "opening_hours": "24h",
    },
    {
        "id": "hdb_101",
        "name": "HDB Block 101",
        "type": "residential",
        "x": 18,
        "y": 72,
        "opening_hours": "24h",
    },
    {
        "id": "hdb_205",
        "name": "HDB Block 205",
        "type": "residential",
        "x": 80,
        "y": 74,
        "opening_hours": "24h",
    },
    {
        "id": "office_tower",
        "name": "Tampines Office Tower",
        "type": "office",
        "x": 70,
        "y": 24,
        "opening_hours": "08:00-19:00",
    },
    {
        "id": "school",
        "name": "Tampines Primary School",
        "type": "school",
        "x": 28,
        "y": 28,
        "opening_hours": "07:00-17:00",
    },
    {
        "id": "hospital",
        "name": "Community Hospital",
        "type": "hospital",
        "x": 50,
        "y": 14,
        "opening_hours": "24h",
    },
    {
        "id": "pharmacy",
        "name": "Guardian Pharmacy",
        "type": "competitor",
        "x": 88,
        "y": 36,
        "opening_hours": "10:00-22:00",
    },
]

ROUTES = [
    {
        "origin": "hdb_101",
        "destination": "office_tower",
        "mode": "walk+bus",
        "distance_m": 1850,
        "duration_min": 22,
        "passes_shell": True,
        "shell_detour_m": 70,
    },
    {
        "origin": "office_tower",
        "destination": "hdb_101",
        "mode": "walk+bus",
        "distance_m": 1850,
        "duration_min": 24,
        "passes_shell": True,
        "shell_detour_m": 70,
    },
    {
        "origin": "hdb_205",
        "destination": "hospital",
        "mode": "bus",
        "distance_m": 1650,
        "duration_min": 18,
        "passes_shell": True,
        "shell_detour_m": 110,
    },
    {
        "origin": "hospital",
        "destination": "hdb_205",
        "mode": "bus",
        "distance_m": 1650,
        "duration_min": 19,
        "passes_shell": True,
        "shell_detour_m": 110,
    },
    {
        "origin": "hdb_101",
        "destination": "school",
        "mode": "walk",
        "distance_m": 650,
        "duration_min": 9,
        "passes_shell": False,
        "shell_detour_m": 420,
    },
    {
        "origin": "school",
        "destination": "hdb_101",
        "mode": "walk",
        "distance_m": 650,
        "duration_min": 10,
        "passes_shell": False,
        "shell_detour_m": 420,
    },
    {
        "origin": "hospital",
        "destination": "shell_select",
        "mode": "walk",
        "distance_m": 430,
        "duration_min": 6,
        "passes_shell": True,
        "shell_detour_m": 0,
    },
    {
        "origin": "office_tower",
        "destination": "shell_select",
        "mode": "walk",
        "distance_m": 520,
        "duration_min": 7,
        "passes_shell": True,
        "shell_detour_m": 0,
    },
    {
        "origin": "pharmacy",
        "destination": "shell_select",
        "mode": "walk",
        "distance_m": 780,
        "duration_min": 11,
        "passes_shell": True,
        "shell_detour_m": 0,
    },
    {
        "origin": "hdb_205",
        "destination": "office_tower",
        "mode": "drive",
        "distance_m": 2100,
        "duration_min": 8,
        "passes_shell": False,
        "shell_detour_m": 260,
    },
    {
        "origin": "office_tower",
        "destination": "hdb_205",
        "mode": "drive",
        "distance_m": 2150,
        "duration_min": 9,
        "passes_shell": False,
        "shell_detour_m": 260,
    },
]

# Canonical persona library for convenience-retail demand simulation.
# Do not rename these personas; downstream simulation and reports depend on these titles.
PERSONAS = [
    {
        "id": "persona_01",
        "name": "The Morning Rusher",
        "agent_name": "Alex",
        "type": "morning_rusher",
        "age_range": "28-38",
        "peak_hours": "6:45 AM-9:00 AM weekdays",
        "travel_mode": "MRT / Bus",
        "frequency": "4-5x/week",
        "home": "circuit_road_market",
        "work": "mattar_mrt",
        "transport": "bus",
        "need_tags": ["coffee", "drinks", "snacks", "speed", "convenience"],
        "price_sensitivity": "medium",
        "current_behaviour": "Grabs coffee, Pokka or 100Plus, occasionally a bun or sandwich. Highly habitual and rarely browses.",
        "purchase_trigger": "Speed above all. Converts when the product is at eye level near the counter and takes zero decision effort.",
        "singapore_context": "Compares selected store instinctively with Cheers, 7-Eleven, and FairPrice Xpress on commuter routes.",
        "simulation_notes": "Trigger between 7:00-8:30 AM; product must be understood in under 60 seconds.",
        "schedule": [
            {"time": "07:05", "place": "circuit_road_market", "activity": "leaves nearby HDB area for commute"},
            {"time": "07:18", "place": "shell_select", "activity": "90-second commuter stop"},
            {"time": "07:35", "place": "mattar_mrt", "activity": "continues toward MRT"},
        ],
    },
    {
        "id": "persona_02a",
        "name": "School Run Parent (Car)",
        "agent_name": "Jordan",
        "type": "school_run_parent_car",
        "age_range": "32-48",
        "peak_hours": "7:00 AM-8:15 AM, 1:30 PM-3:30 PM",
        "travel_mode": "Private car",
        "frequency": "2-3x/week",
        "home": "ibis_macpherson",
        "work": "little_seeds",
        "transport": "drive",
        "need_tags": ["family", "child", "medicine", "household", "forecourt_visibility"],
        "price_sensitivity": "low",
        "current_behaviour": "Primarily fuels and leaves; may grab a drink or snack for the child or household staples.",
        "purchase_trigger": "Kid-friendly products visible from the pump area, familiar brands, and quick household solutions.",
        "singapore_context": "School drop-off is intense, and car-owning parents are time-pressed higher-income households.",
        "simulation_notes": "Store entry is conditional on visibility from the forecourt or a specific household need.",
        "schedule": [
            {"time": "07:10", "place": "ibis_macpherson", "activity": "starts school run by car"},
            {"time": "07:25", "place": "little_seeds", "activity": "school drop-off"},
            {"time": "07:45", "place": "shell_select", "activity": "fuel-linked stop with limited browsing"},
        ],
    },
    {
        "id": "persona_02b",
        "name": "School Run Parent (Walking)",
        "agent_name": "Casey",
        "type": "school_run_parent_walking",
        "age_range": "30-45",
        "peak_hours": "7:15 AM-8:30 AM, 1:00 PM-3:00 PM",
        "travel_mode": "Walking",
        "frequency": "3-4x/week",
        "home": "circuit_road_market",
        "work": "little_seeds",
        "transport": "walk",
        "need_tags": ["family", "child", "snacks", "household", "value"],
        "price_sensitivity": "medium",
        "current_behaviour": "May buy a drink, snack for the child, or small household item. More likely to browse than car parents.",
        "purchase_trigger": "Clearly useful for household or child, value-for-money, and saves a supermarket trip.",
        "singapore_context": "Dense HDB neighbourhoods make home, school, and selected store plausible within a 10-minute walk.",
        "simulation_notes": "Higher store-entry probability than 02A with moderate purchase probability.",
        "schedule": [
            {"time": "07:20", "place": "circuit_road_market", "activity": "walks from HDB area"},
            {"time": "07:35", "place": "little_seeds", "activity": "school drop-off"},
            {"time": "07:50", "place": "shell_select", "activity": "neighbourhood browse after drop-off"},
            {"time": "08:05", "place": "circuit_road_market", "activity": "returns toward home"},
        ],
    },
    {
        "id": "persona_03",
        "name": "The Elderly Neighbourhood Regular",
        "agent_name": "Riley",
        "type": "elderly_neighbourhood_regular",
        "age_range": "62-78",
        "peak_hours": "9:00 AM-12:00 PM",
        "travel_mode": "Walking",
        "frequency": "3-5x/week",
        "home": "circuit_road_market",
        "work": None,
        "transport": "walk",
        "need_tags": ["medicine", "health", "familiar_brand", "daily_necessities", "price_sensitive"],
        "price_sensitivity": "high",
        "current_behaviour": "Buys familiar, trusted products and daily necessities; unlikely to try unknown products without clear signage or staff recommendation.",
        "purchase_trigger": "Familiarity, trust, recognised brands, multilingual labelling, and health-oriented messaging.",
        "singapore_context": "Heartland selected store stores serve elderly residents heavily during off-peak hours.",
        "simulation_notes": "Slower walking speed, longer dwell time, browses and compares prices.",
        "schedule": [
            {"time": "09:15", "place": "circuit_road_market", "activity": "morning market and food centre visit"},
            {"time": "10:05", "place": "shell_select", "activity": "habitual neighbourhood stop"},
            {"time": "10:40", "place": "st_johns_home", "activity": "continues morning walking circuit"},
        ],
    },
    {
        "id": "persona_04",
        "name": "The Late Night Lone Wolf",
        "agent_name": "Morgan",
        "type": "late_night_lone_wolf",
        "age_range": "20-34",
        "peak_hours": "10:00 PM-1:30 AM",
        "travel_mode": "Walking / Grab",
        "frequency": "2-4x/week",
        "home": "mattar_mrt",
        "work": "super_thai",
        "transport": "walk",
        "need_tags": ["snacks", "energy_drinks", "ice_cream", "novelty", "late_shift"],
        "price_sensitivity": "medium",
        "current_behaviour": "Buys chips, instant noodles, energy drinks, ice cream, cigarettes, and isotonic drinks.",
        "purchase_trigger": "Novelty, indulgence, exclusivity, limited editions, and treat-like products.",
        "singapore_context": "selected store may be one of the few 24-hour retail options in quiet neighbourhood hours.",
        "simulation_notes": "Run from 10 PM-1 AM; moderate to high dwell time and impulse purchase probability.",
        "schedule": [
            {"time": "22:15", "place": "super_thai", "activity": "leaves late meal or shift nearby"},
            {"time": "22:40", "place": "shell_select", "activity": "late-night impulse browse"},
            {"time": "23:05", "place": "mattar_mrt", "activity": "heads home by ride or transit"},
        ],
    },
    {
        "id": "persona_05",
        "name": "Weekend Family Shopper",
        "agent_name": "Taylor",
        "type": "weekend_family_shopper",
        "age_range": "33-52",
        "peak_hours": "10:00 AM-6:00 PM weekends",
        "travel_mode": "Car / Walk",
        "frequency": "1-2x/week",
        "home": "macpherson_mall",
        "work": "grantral_mall",
        "transport": "drive",
        "need_tags": ["family", "bundle", "multipack", "drinks", "snacks", "household"],
        "price_sensitivity": "medium",
        "current_behaviour": "Buys drinks for the family, snacks, ice cream, meal items, and occasional household staples.",
        "purchase_trigger": "Family value, bundle deals, multipacks, and small weekend treats.",
        "singapore_context": "Weekend errands and family recreation make selected store a top-up stop, not a full shop.",
        "simulation_notes": "Weekend-only; higher dwell time, purchase influenced by children in the group.",
        "schedule": [
            {"time": "11:00", "place": "macpherson_mall", "activity": "weekend errand start"},
            {"time": "11:45", "place": "shell_select", "activity": "family top-up stop"},
            {"time": "12:20", "place": "grantral_mall", "activity": "continues weekend errands"},
        ],
    },
    {
        "id": "persona_06",
        "name": "The EV / Fuel Regular",
        "agent_name": "Jamie",
        "type": "ev_fuel_regular",
        "age_range": "30-58",
        "peak_hours": "Variable",
        "travel_mode": "Private car / EV",
        "frequency": "2-4x/week",
        "home": "macpherson_mall",
        "work": "shell_select",
        "transport": "drive",
        "need_tags": ["coffee", "meal", "dwell_time", "ev_charging", "premium"],
        "price_sensitivity": "low",
        "current_behaviour": "Buys coffee or nothing while waiting; EV users have significant dwell time and little to do.",
        "purchase_trigger": "Anything that makes waiting productive or enjoyable, especially quality coffee or meal options.",
        "singapore_context": "EV adoption and charging dwell time make this persona increasingly important.",
        "simulation_notes": "Differentiate 5-minute fuel stops from 20-40 minute EV charging stops.",
        "schedule": [
            {"time": "08:10", "place": "macpherson_mall", "activity": "drives through locality"},
            {"time": "08:25", "place": "shell_select", "activity": "fuel or EV charging dwell time"},
            {"time": "09:05", "place": "mattar_mrt", "activity": "continues onward after stop"},
        ],
    },
    {
        "id": "persona_07",
        "name": "The Lunch Breaker",
        "agent_name": "Avery",
        "type": "lunch_breaker",
        "age_range": "24-45",
        "peak_hours": "11:45 AM-2:00 PM weekdays",
        "travel_mode": "Walking",
        "frequency": "3-4x/week",
        "home": "macpherson_mall",
        "work": "grantral_mall",
        "transport": "walk",
        "need_tags": ["lunch", "food", "drink", "dessert", "quality_value"],
        "price_sensitivity": "medium",
        "current_behaviour": "Buys a quick meal, cold drink, or dessert; compares selected store against nearby F&B.",
        "purchase_trigger": "A satisfying lunch with strong price-quality ratio.",
        "singapore_context": "Hawker centres, food courts, and cafes compete strongly in the 12-2 PM lunch window.",
        "simulation_notes": "Evaluate F&B alternatives in the same walking radius.",
        "schedule": [
            {"time": "11:50", "place": "grantral_mall", "activity": "starts lunch break"},
            {"time": "12:10", "place": "shell_select", "activity": "quick lunch or post-lunch drink stop"},
            {"time": "12:40", "place": "macpherson_mall", "activity": "returns toward workplace"},
        ],
    },
    {
        "id": "persona_08",
        "name": "The Fitness Regular",
        "agent_name": "Quinn",
        "type": "fitness_regular",
        "age_range": "24-42",
        "peak_hours": "6:00 AM-8:00 AM, 6:30 PM-9:00 PM",
        "travel_mode": "Walk / Run",
        "frequency": "3-5x/week",
        "home": "mattar_mrt",
        "work": "circuit_road_market",
        "transport": "walk",
        "need_tags": ["hydration", "isotonic", "protein", "low_sugar", "health"],
        "price_sensitivity": "medium",
        "current_behaviour": "Buys 100Plus, water, coconut water, protein bars, or light snacks.",
        "purchase_trigger": "Health-aligned framing first, with some openness to post-workout indulgence.",
        "singapore_context": "Healthier SG, PCNs, gyms, and running routes create repeat fitness foot traffic.",
        "simulation_notes": "Model both AM and PM sessions and post-workout emotional state.",
        "schedule": [
            {"time": "18:45", "place": "mattar_mrt", "activity": "finishes evening run route"},
            {"time": "19:05", "place": "shell_select", "activity": "post-workout hydration stop"},
            {"time": "19:25", "place": "circuit_road_market", "activity": "walks home through neighbourhood"},
        ],
    },
    {
        "id": "persona_09",
        "name": "The Transient Traveller",
        "agent_name": "Rowan",
        "type": "transient_traveller",
        "age_range": "28-58",
        "peak_hours": "Variable",
        "travel_mode": "Car / Grab",
        "frequency": "Infrequent",
        "home": "ibis_macpherson",
        "work": "macpherson_mall",
        "transport": "drive",
        "need_tags": ["water", "snacks", "medicine", "toiletries", "clear_packaging", "local"],
        "price_sensitivity": "low",
        "current_behaviour": "Buys familiar brands, water, snacks, practical travel items, or local Singaporean takeaways.",
        "purchase_trigger": "Clarity and discoverability; bold packaging and obvious use case.",
        "singapore_context": "Tourists, expressway drivers, and business travellers buy on instinct and need universal legibility.",
        "simulation_notes": "Increase weight near tourist or expressway corridors; calculate route from hotel or attraction node.",
        "schedule": [
            {"time": "15:30", "place": "ibis_macpherson", "activity": "leaves hotel"},
            {"time": "15:45", "place": "shell_select", "activity": "unplanned convenience stop"},
            {"time": "16:05", "place": "macpherson_mall", "activity": "continues local errand"},
        ],
    },
    {
        "id": "persona_10",
        "name": "The Cabbie / Grab Driver",
        "agent_name": "Sky",
        "type": "cabbie_grab_driver",
        "age_range": "30-62",
        "peak_hours": "All hours",
        "travel_mode": "Private hire car / taxi",
        "frequency": "Daily / multiple times per day",
        "home": "mattar_mrt",
        "work": "shell_select",
        "transport": "drive",
        "need_tags": ["coffee", "quick_meal", "energy_drinks", "isotonic", "value", "speed"],
        "price_sensitivity": "high",
        "current_behaviour": "Coffee, quick meals, energy drinks, cigarettes, isotonic drinks; loyal and extremely price-conscious.",
        "purchase_trigger": "Value and speed; fair price and clear positioning near counter or coffee machine.",
        "singapore_context": "Drivers share rest areas and WhatsApp networks; strong product fit spreads through driver word-of-mouth.",
        "simulation_notes": "Run across multiple slots in one day; continuous presence and fuel/charging cadence.",
        "schedule": [
            {"time": "05:45", "place": "shell_select", "activity": "pre-shift coffee and fuel stop"},
            {"time": "13:35", "place": "shell_select", "activity": "between-rides quick meal stop"},
            {"time": "23:55", "place": "shell_select", "activity": "post-shift late stop"},
        ],
    },
]


def scenario_payload():
    return {
        "locality": {
            "name": "MacPherson 2 km POC Zone",
            "center": LOCALITY_CENTER,
            "bounds": LOCALITY_BOUNDS,
            "catchment_snapshot": CATCHMENT_SNAPSHOT,
            "rule": "For this POC, places, personas, movement, and responses are constrained to this fixed MacPherson 2 km locality.",
        },
        "places": PLACES,
        "routes": ROUTES,
        "personas": PERSONAS,
        "default_product": {
            "name": "Paracetamol 500mg",
            "category": "medicine",
            "price_sgd": 4.90,
            "notes": "OTC pain and fever relief in a 20-tablet pack",
        },
    }
