PLACES = [
    {
        "id": "shell_select",
        "name": "Shell Select Tampines Link",
        "type": "shell_select",
        "x": 52,
        "y": 48,
        "opening_hours": "24h",
    },
    {
        "id": "hdb_101",
        "name": "HDB Block 101",
        "type": "residential",
        "x": 18,
        "y": 72,
        "opening_hours": "24h",
    },
    {
        "id": "hdb_205",
        "name": "HDB Block 205",
        "type": "residential",
        "x": 80,
        "y": 74,
        "opening_hours": "24h",
    },
    {
        "id": "office_tower",
        "name": "Tampines Office Tower",
        "type": "office",
        "x": 70,
        "y": 24,
        "opening_hours": "08:00-19:00",
    },
    {
        "id": "school",
        "name": "Tampines Primary School",
        "type": "school",
        "x": 28,
        "y": 28,
        "opening_hours": "07:00-17:00",
    },
    {
        "id": "hospital",
        "name": "Community Hospital",
        "type": "hospital",
        "x": 50,
        "y": 14,
        "opening_hours": "24h",
    },
    {
        "id": "pharmacy",
        "name": "Guardian Pharmacy",
        "type": "competitor",
        "x": 88,
        "y": 36,
        "opening_hours": "10:00-22:00",
    },
]

ROUTES = [
    {
        "origin": "hdb_101",
        "destination": "office_tower",
        "mode": "walk+bus",
        "distance_m": 1850,
        "duration_min": 22,
        "passes_shell": True,
        "shell_detour_m": 70,
    },
    {
        "origin": "office_tower",
        "destination": "hdb_101",
        "mode": "walk+bus",
        "distance_m": 1850,
        "duration_min": 24,
        "passes_shell": True,
        "shell_detour_m": 70,
    },
    {
        "origin": "hdb_205",
        "destination": "hospital",
        "mode": "bus",
        "distance_m": 1650,
        "duration_min": 18,
        "passes_shell": True,
        "shell_detour_m": 110,
    },
    {
        "origin": "hospital",
        "destination": "hdb_205",
        "mode": "bus",
        "distance_m": 1650,
        "duration_min": 19,
        "passes_shell": True,
        "shell_detour_m": 110,
    },
    {
        "origin": "hdb_101",
        "destination": "school",
        "mode": "walk",
        "distance_m": 650,
        "duration_min": 9,
        "passes_shell": False,
        "shell_detour_m": 420,
    },
    {
        "origin": "school",
        "destination": "hdb_101",
        "mode": "walk",
        "distance_m": 650,
        "duration_min": 10,
        "passes_shell": False,
        "shell_detour_m": 420,
    },
    {
        "origin": "hospital",
        "destination": "shell_select",
        "mode": "walk",
        "distance_m": 430,
        "duration_min": 6,
        "passes_shell": True,
        "shell_detour_m": 0,
    },
    {
        "origin": "office_tower",
        "destination": "shell_select",
        "mode": "walk",
        "distance_m": 520,
        "duration_min": 7,
        "passes_shell": True,
        "shell_detour_m": 0,
    },
    {
        "origin": "pharmacy",
        "destination": "shell_select",
        "mode": "walk",
        "distance_m": 780,
        "duration_min": 11,
        "passes_shell": True,
        "shell_detour_m": 0,
    },
    {
        "origin": "hdb_205",
        "destination": "office_tower",
        "mode": "drive",
        "distance_m": 2100,
        "duration_min": 8,
        "passes_shell": False,
        "shell_detour_m": 260,
    },
    {
        "origin": "office_tower",
        "destination": "hdb_205",
        "mode": "drive",
        "distance_m": 2150,
        "duration_min": 9,
        "passes_shell": False,
        "shell_detour_m": 260,
    },
]

PERSONAS = [
    {
        "id": "p001",
        "name": "Aisha",
        "type": "working_mother",
        "home": "hdb_101",
        "work": "office_tower",
        "transport": "walk+bus",
        "need_tags": ["family", "medicine", "convenience", "after_work"],
        "price_sensitivity": "medium",
        "schedule": [
            {"time": "07:20", "place": "school", "activity": "drops child at school"},
            {"time": "08:30", "place": "office_tower", "activity": "works at office"},
            {"time": "18:25", "place": "shell_select", "activity": "passes Shell Select on route home"},
            {"time": "19:05", "place": "hdb_101", "activity": "returns home"},
        ],
    },
    {
        "id": "p002",
        "name": "Daniel",
        "type": "hospital_nurse",
        "home": "hdb_205",
        "work": "hospital",
        "transport": "bus",
        "need_tags": ["medicine", "late_shift", "convenience", "healthcare"],
        "price_sensitivity": "low",
        "schedule": [
            {"time": "06:45", "place": "hospital", "activity": "starts hospital shift"},
            {"time": "15:30", "place": "shell_select", "activity": "short stop after shift"},
            {"time": "16:05", "place": "hdb_205", "activity": "returns home"},
        ],
    },
    {
        "id": "p003",
        "name": "Mr Tan",
        "type": "elderly_resident",
        "home": "hdb_101",
        "work": None,
        "transport": "walk",
        "need_tags": ["medicine", "nearby", "price_sensitive"],
        "price_sensitivity": "high",
        "schedule": [
            {"time": "09:30", "place": "hdb_101", "activity": "morning walk near home"},
            {"time": "10:15", "place": "pharmacy", "activity": "prefers pharmacy when open"},
            {"time": "21:45", "place": "shell_select", "activity": "only nearby 24h option at night"},
        ],
    },
    {
        "id": "p004",
        "name": "Priya",
        "type": "office_worker",
        "home": "hdb_205",
        "work": "office_tower",
        "transport": "drive",
        "need_tags": ["snacks", "quick_stop", "after_work"],
        "price_sensitivity": "medium",
        "schedule": [
            {"time": "08:50", "place": "office_tower", "activity": "arrives at office"},
            {"time": "12:20", "place": "shell_select", "activity": "quick lunch snack stop"},
            {"time": "18:40", "place": "hdb_205", "activity": "drives home"},
        ],
    },
]


def scenario_payload():
    return {
        "places": PLACES,
        "routes": ROUTES,
        "personas": PERSONAS,
        "default_product": {
            "name": "Paracetamol 500mg",
            "category": "medicine",
            "price_sgd": 4.90,
            "notes": "OTC pain and fever relief in a 20-tablet pack",
        },
    }
